version: '3.8'
services:
  p2p:
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        max_attempts: 2
      resources:
        limits:
          cpus: "0.1"
          memory: '30M'
    image: osxdk/p2p:latest
    environment:
      - email=$email
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
